import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { api } from "~/utils/api";
import React from "react";

const Home: NextPage = () => {
  const getAll = api.example.getAll.useQuery();
  const { mutate: createMutate } = api.example.create.useMutation();
  const messages = getAll?.data;
  const [form, setForm] = useState({
    name: '',
    message: '',
    email: ''
  })

  const postMessage = async () => {
    const mutation = createMutate(form)
    
  }



  const handleSubmit = function (e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    console.log(form)
  }

  const handleChange = function (e: (React.ChangeEvent<HTMLInputElement> | React.ChangeEvent<HTMLTextAreaElement>)) {

    setForm({
      ...form,
      [e.target.name]: e.target.value,
    })
  }

  if (!messages) {
    return <div>loading...</div>
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Contact App</h1>
        <form style={{
          display: 'flex',
          flexDirection: 'column',
          gap: '10px'

        }}
          onSubmit={postMessage}>
          <input type="text" name='name' value={form.name} onChange={handleChange} />
          <input type="text" name='email' value={form.email} onChange={handleChange} />
          <textarea name='message' value={form.message} onChange={handleChange} />
          <button>submit</button>
        </form>
        {messages.map(message =>
          <div style={{ border: '2px solid white', color: 'white', margin: '5px', padding: '5px' }} key={message.id} >
            <h3>{message.message}</h3>
            <Link href={`messages/${message.id}`}><p>{message.name}</p></Link>
          </div>)
        }
      </main >
    </>
  );
};

export default Home;
